# Site/SEO settings
email: hello@rthr.me
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: UA-52979039-1

name: Arthur Lockman
title: "[Untitled1.cs]"
description: >
  A little bit of everything
url: https://rthr.me
twitter_username: arthurlockman
default_img: https://static.rthr.me/images/epcot-ball-pattern_2020-02-11.jpeg
social:
  - name: twitter
    url: https://twitter.com/arthurlockman
  - name: instagram
    url: https://www.instagram.com/arthurlockman/
  - name: linkedin
    url: https://www.linkedin.com/in/arthurlockman/
  - name: github
    url: https://github.com/arthurlockman

# Contact settings
contact_img: https://static.rthr.me/images/epcot-ball-pattern_2020-02-11.jpeg
formcarry: https://formcarry.com/s/HnYDwxhAEGI

# Disqus settings
# disqus: test-apkdzgmqhj

# MailChimp settings
# mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
# mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Arthur Lockman
    bio: Arthur Lockman is a .NET Core and web developer based in Massachusetts. He's also an amateur photographer specializing in Walt Disney World and small events photography.
    url: https://rthr.me

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: '[Untitled1.cs]'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
  - .idea
  - package-lock.yml
  - cloudformation.yml
